group 'auto.whiterhino.module.message_bridge'
version '1.0'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
    }
}

rootProject.allprojects {
    repositories {
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'auto.whiterhino.module.message_bridge'
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 16
    }
}



dependencies {
    compileOnly 'com.github.getActivity:XXPermissions:18.63'
    compileOnly 'com.amap.api:navi-3dmap:10.0.600_3dmap10.0.600'
    compileOnly 'com.geyifeng.immersionbar:immersionbar:3.2.2'
}
